name: Test runner

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: reviews
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2

    - name: Install deps and run tests
      run: cd backend && npm i && npm test

      env:
        PG_DB: reviews
        PG_USER: user
        PG_PASSWORD: password
        HOST: localhost